package ibnk.models.internet.enums;



public enum EventCode {
    FIRST_LOGIN,
    RESET_PIN,
    VALIDATE_TRANSACTION,
    VALIDATE_BENEFICIARY,
    VALIDATE_INTERNAL_TRANSACTION,
    ACCOUNT_TRANSFER,
    ANOTHER_DEVICE_SIGNED_IN,
    INTERNET_BAKING_SUBSCRIPTION,
    DOUBLE_AUTHENTICATION,
    RESET_PASSWORD,
    REGISTRATION_REQUEST,
    DEPOSIT_COMPLETED,
    WITHDRAWAL_COMPLETED,
    SUBSCRIPTION_REQUEST,
    OPEN_ACCOUNT_REQUEST,
    REJECTED_ACCOUNT_REQUEST,
    SUBSCRIPTION_PASSWORD,
    E_ACCOUNT_STATEMENT,
    BENEFICIARY_APPROVED,
    BENEFICIARY_NOTAPPROVED,
}
