package ibnk.models.internet.enums;


public enum OtpEnum {
    RESET_PASSWORD,
    UPDATE_PIN,
    RESET_PIN,
    FIRST_LOGIN,
    NEW_DEVICE_LOGIN,
    SUBSCRIBER,
    SUBSCRIPTION_REQUEST,
    DOUBLE_AUTHENTICATION,
    OPEN_ACCOUNT_REQUEST,
    VALIDATE_TRANSACTION,
    VALIDATE_BENEFICIARY,
    VALIDATE_INTERNAL_TRANSACTION
}
